NUM_CLASS: 10
OUTPUT_DIR: "train_dir/config_cifar10_R50_1gpu"
SAVE_EPOCH_PERIOD: 10
PRINT_ITER_PERIOD: 5
TEST_EPOCH_PERIOD: 10

MODEL:
  NETWORK: ["resnet50", []]
  NETWORK_STRIDE: [2, 1, 2, 2, 1]

SOLVER:
  MAX_EPOCH: 350
  BATCH_SIZE: 512
  BASE_LR: 0.4
  STEPS: [150, 250]

TRAIN:
  TRANSFORMS:
    - ["RandomCrop", [["size", 32], ["padding", 4], ]]
    - ["RandomHorizontalFlip", []]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
TEST:
  BATCH_SIZE: 512
  TRANSFORMS:
    - ["Resize", [["size", 32], ]]
    - ["ToTensor", []]
    - ["Normalize", [["mean", [0.485, 0.456, 0.406]], ["std", [0.229, 0.224, 0.225]], ]]
